"""Stage 2 — the greeting, in two parts.

  Part 1 — the hello: a short, casual, spoken welcome that notes what the visitor
    is wearing. It is NOT generated by the model — it is rendered by plain string
    substitution from one of five fixed templates (rotated round-robin), with the
    CLIP compliment phrase (clip_tags.compliment) dropped into a 'love the {…}'
    slot. The terse host voice is fixed copy, so a template is both instant and
    more reliable than a 0.8B model that tends to parrot the example outfits; the
    two greetings that used to seed the model's prompt are now templates themselves.
  Part 2 — the question card: a few short, open questions about generative AI, on
    one of seventeen randomly chosen themes (questions.py), so the visitor argues and
    wonders for themselves rather than watching passively. A small Qwen3.5 (GGUF, CPU
    via llama-cpp-python) generates it UNDER the acrostic mask (acrostic.py; grammar
    idea from github.com/lsb/sidechat) — its length suits a handful of questions.

The model is loaded lazily so nothing heavy happens until a visitor faces the
camera; only the question card (Part 2) uses it.
"""

from __future__ import annotations

from dataclasses import dataclass

from acrostic import acrostic_from_env
from face_gate import FaceResult
from models import ensure_gguf
from questions import QUESTIONS_SYSTEM, build_questions_prompt, pick_topic

# Part 1 register: a short, casual greeting — three plain beats: a quick hi (plus one
# compliment on the most distinctive thing the visitor is wearing, when CLIP read
# one), the gallery's name, and one warm practical line (browse, much is for sale).
# No model: the hello is rendered from one of these five templates by plain string
# substitution, rotated round-robin so consecutive visitors never hear the same one.
# Each template is (complimenting opener, plain opener, body); the plain opener is
# used when CLIP read no outfit. Tokens: {greet} opens the line (singular/plural),
# {you} is "you"/"you all", {c} is the CLIP compliment phrase (e.g. "red hoodie").
# Keep the copy plain and friendly — no invented prices/websites, no exclamation
# marks, no questions — matching the two example greetings these grew out of.
_HELLO_TEMPLATES = (
    ("{greet}, love the {c}.", "{greet}, welcome in.",
     "Welcome to the intersection of art and technology. "
     "Stay as long as {you} like, and a lot of the work here is for sale."),
    ("{greet}, that {c} is great.", "{greet}, good to have {you} in.",
     "This is the intersection of art and technology. "
     "Browse as long as {you} like, and a lot of these pieces are for sale."),
    ("{greet}, the {c} really works.", "{greet}, thanks for stopping in.",
     "You've reached the intersection of art and technology. "
     "Have a look around as long as {you} like, and much of the work here is for sale."),
    ("{greet}, nice {c}.", "{greet}, come on in.",
     "Welcome to the intersection of art and technology. "
     "Wander as long as {you} like, and a lot of the work here is for sale."),
    ("{greet}, that {c} caught my eye.", "{greet}, welcome.",
     "This is the intersection of art and technology. "
     "Stick around as long as {you} like, and many of these pieces are for sale."),
)


def render_hello(compliment: str | None, group_size: int = 1, index: int = 0) -> str:
    """Render the spoken hello from template ``index`` (mod five) by plain string
    substitution — no model. With a compliment we use the template's complimenting
    opener; without one (CLIP read nothing confidently) we use its plain opener. For
    a group (group_size >= 2) the hello is addressed in the plural, with the one
    outfit we read (the closest visitor's) used as the compliment — so 'love the
    jacket' lands on a person, not the crowd. Kept module-level so a tone harness and
    the live greeter render identically (no drift between test and ship)."""
    plural = group_size >= 2
    opener_c, opener_plain, body = _HELLO_TEMPLATES[index % len(_HELLO_TEMPLATES)]
    opener = opener_c if compliment else opener_plain
    return f"{opener} {body}".format(
        greet="Hi everyone" if plural else "Hi",
        you="you all" if plural else "you",
        c=compliment or "")

@dataclass
class Greeting:
    """What a visitor gets: the spoken hello (Part 1) and the acrostic question
    card (Part 2) on a randomly chosen theme."""
    hello: str
    questions: str
    topic: str


class Greeter:
    def __init__(self, size: str = "0.8B", n_ctx: int = 2048, n_threads: int | None = None,
                 paragraphs: tuple[str, ...] | None = None,
                 min_line: int | None = None, max_line: int | None = None):
        self.size = size
        self.n_ctx = n_ctx
        self.n_threads = n_threads
        # The acrostic constraint (used for the Part 2 question card) comes from the
        # environment (WELCOME_ACROSTIC / WELCOME_MIN_LINE / WELCOME_MAX_LINE) so it
        # can be tuned without code edits; an explicit argument still wins.
        env_paragraphs, env_min, env_max = acrostic_from_env()
        self.paragraphs = env_paragraphs if paragraphs is None else paragraphs
        self.min_line = env_min if min_line is None else min_line
        self.max_line = env_max if max_line is None else max_line
        self._llm = None         # lazy
        self._card_dec = None    # lazy: Part 2 question card, acrostic-masked
        self._hello_i = 0        # round-robin cursor over _HELLO_TEMPLATES

    def load(self) -> "Greeter":
        """Eagerly load the model + compile the grammar (so callers can time it)."""
        self._ensure_card_decoder()
        return self

    def _ensure_llm(self):
        if self._llm is None:
            from llama_cpp import Llama

            self._llm = Llama(
                model_path=str(ensure_gguf(self.size)),
                n_ctx=self.n_ctx,
                n_threads=self.n_threads,
                verbose=False,
            )
        return self._llm

    def _ensure_card_decoder(self):
        if self._card_dec is None:
            from acrostic import AcrosticDecoder

            # Only Part 2 (the question card) uses the model now; the hello is
            # templated. The card runs under the configured acrostic grammar mask.
            llm = self._ensure_llm()
            self._card_dec = AcrosticDecoder(llm, paragraphs=self.paragraphs,
                                             min_line=self.min_line, max_line=self.max_line)
        return self._card_dec

    def greet(self, face: FaceResult, compliment: str | None = None,
              on_delta=None, abort=None) -> Greeting:
        """Generate the greeting. Part 1 (the spoken hello) is rendered instantly
        from the next template; Part 2 (the question card) is generated by the model.
        If on_delta is given it is called as on_delta(part, piece): once with the
        whole hello ("hello"), once with the chosen theme ("topic") before the model
        runs, then for every streamed card token ("card"), so a live display shows the
        hello and the question first, and the card as the model writes it. Other sinks
        (the printer) use the finished text in the returned Greeting.

        ``abort`` is forwarded to the streamed card (see AcrosticDecoder.generate):
        when a group's worth of visitors all leave mid-card it raises
        GenerationAborted, which the kiosk catches to drop the half-written card.

        How many faces are turned to the camera (``face.facing_count``) decides
        whether the hello is addressed to one visitor or to the group in the plural."""
        card_dec = self._ensure_card_decoder()
        group_size = max(1, getattr(face, "facing_count", 1) or 1)
        # Part 1: rendered instantly from the next template (no model). Emit it as one
        # delta so a live display shows the hello at once, then streams the card.
        hello = render_hello(compliment, group_size, self._next_hello_index())
        if on_delta:
            on_delta("hello", hello)
        # Emit the theme the model is about to answer *before* its output, so a live
        # display can show the question first and the card it grows underneath it.
        topic = pick_topic()
        if on_delta:
            on_delta("topic", topic)
        questions = card_dec.generate(
            QUESTIONS_SYSTEM, build_questions_prompt(topic),
            on_delta=(lambda d: on_delta("card", d)) if on_delta else None, abort=abort)
        return Greeting(hello=hello, questions=questions, topic=topic)

    def _next_hello_index(self) -> int:
        """Advance the round-robin cursor over the five hello templates."""
        i = self._hello_i
        self._hello_i = (i + 1) % len(_HELLO_TEMPLATES)
        return i
